version: '3'

services:

  postgres:
    image: postgres:13-alpine
    container_name: postgres-13
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db_local_data:/var/lib/postgresql/data
      - ./db/public.sql:/docker-entrypoint-initdb.d/1-schema.sql

# Volumes
volumes:
  db_local_data:
    external: true
